# Generated by Django 3.2.3 on 2021-05-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='firstname')),
                ('last_name', models.CharField(max_length=100, verbose_name='lastname')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('company', models.CharField(max_length=100, verbose_name='company')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
            ],
            options={
                'verbose_name': 'Customer',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['first_name'], name='idx_customer_first_name'),
        ),
    ]
